In [52]:
import pandas as pd

In [53]:
pd.set_option('display.max_columns', None)

In [54]:
import requests
from bs4 import BeautifulSoup

In [55]:
url = "https://soco.seoul.go.kr/youth/pgm/home/yohome/maplist.json"
head = {"User-Agent":
"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36"}
response = requests.post(url, headers= head)
ansim = response.json()

In [56]:
ansim_df = pd.DataFrame(ansim['mapResultList'])

In [57]:
ansim_df

,rnum,homeCode,mainImgAtchFileId,mainImgAtchFileSeq,adresSi,adresGu,adresRo,adres,adresDetail,homeName,totArea,totFloor,totPeople,optionSubway,presale,presaleNm,movinTerms,movinHoman,houseSupplyNm,managerComp,moneyDeposit,moneyDepositLow,moneyRentalLow,tradPrice,scaleTot,managerPhone,homepage,fnMoneyDeposit,fnMoneyDepositLow,fnMoneyDepositHigh,fnMoneyRentalLow,fnMoneyRentalHigh,fnTradPrice,statusCnt,roomTotArea,regDate,xpos,ypos,houseStrut,subwayLineCd,fileId,fileSn
0,1,20000540,None,None,서울,은평구,갈현동 456-25,은평구 갈현동 456-25,THE STUDIO 163,연신내역 THE STUDIO 163,None,None,NaN,"3호선, 6호선 연신내역 5번출구 236m",C,월세,None,제한없음,None,THE STUDIO 163,None,40000000.0,290000.0,None,163,02-564-4866,http://www.thestudio163.co.kr,-6502,4천0만,8천6백0만,29만,53만,-6502,0,17A,1712125695000,126.9190859,37.6179079,None,"03,06",16d932a39bb04b9cae0ca3653aa07108,1
1,2,20000537,None,None,서울,중랑구,상봉동 118-8,중랑구 상봉동 118-8,상봉동양엔파트,상봉역 상봉동양엔파트,None,None,NaN,"7호선, 경의중앙선, 경춘선 상봉역 5번출구 240m",C,월세,None,제한없음,None,상봉동양엔파트,None,43000000.0,280000.0,None,299,02-493-1006,https://sbnpart.co.kr/index.php,-6502,4천3백0만,1억3천2백0만,28만,76만,-6502,0,18.03(18A),1711088694000,127.0822135,37.5950616,None,"07,12,14",01dccb9cec424549b0f6b671b3e69887,1
2,3,20000366,None,None,서울,중랑구,봉우재로 111,중랑구 봉우재로 111,제이스타상봉,상봉역 제이스타상봉,None,None,0.0,"7호선, 경의중앙선, 경춘선 상봉역 4번출구 324m",C,월세,None,제한없음,None,대원교역상사,None,36000000.0,300000.0,None,83,02-537-4102,https://jstar2030.modoo.at,-6502,3천6백0만,7천6백0만,30만,60만,-6502,0,17.02,1646875909000,127.0852776,37.5926916,None,"07,12,14",73758eda9e5d4d389892785146e89c3b,11
3,4,20000373,None,None,서울,은평구,서오릉로 165,은평구 서오릉로 165,구산주택,구산역 구산주택,None,None,238.0,6호선 구산역 4번출구 258m,C,월세,None,제한없음,None,(주)덕영,None,36000000.0,290000.0,None,238,010-4744-8798,https://duckyoung2016.com/,-6502,3천6백0만,9천1백0만,29만,67만,-6502,0,17A,1649731442000,126.9150401,37.6122404,None,06,209a14a71d2d41f081b06440ae961a4a,29
4,5,20000531,None,None,서울,동작구,노량진동 54-1,동작구 노량진동 54-1,더써밋타워,노량진역 더써밋타워,None,None,NaN,"1호선, 9호선 노량진역 4번출구 40m",C,월세,None,제한없음,None,코레이트노량진역유한회사,None,45000000.0,310000.0,None,299,02-823-5410,https://thesummittower.co.kr/,-6502,4천5백0만,1억9천1백0만,31만,1백0만6만,-6502,0,17.78C,1707093977000,126.9407288,37.5131814,None,"01,09",4ed6311ac1194a6cbe37ff21b81b1041,10
5,6,20000526,None,None,서울시,동작구,대방동 403-14,동작구 대방동 403-14,골든노블레스,신대방삼거리역 골든노블레스,None,None,NaN,신대방삼거리역 3번 출구에서 227m,C,월세,None,제한없음,None,이영희 외 3인,None,34000000.0,240000.0,None,110,070-7609-0100,https://www.db40314.kr/,-6502,3천4백0만,1억2천8백0만,24만,73만,-6502,0,18A,1702259696000,None,None,None,07,b0550f46b6db458daa123d5b77edaf58,1
6,7,20000529,None,None,서울,송파구,문정동 55-6,송파구 문정동 55-6,문정역 마에스트로,문정역 마에스트로,None,None,NaN,8호선 문정역 2번출구 180m,C,월세,None,제한없음,None,문정역마에스트로프로젝트,None,42000000.0,360000.0,None,438,02-3453-9655,https://maestromunjeong.com,-6502,4천2백0만,1억1천6백0만,36만,86만,-6502,0,16A,1704861920000,127.1230586,37.4863628,None,08,920c57725cbe4855b5722e87f81cbab3,1
7,8,20000495,None,None,서울,송파구,잠실동 187-10,송파구 잠실동 187-10,잠실 센트럴파크,잠실새내역 잠실센트럴파크,None,None,NaN,2호선 잠실새내역 4번출구 301m,C,월세,None,제한없음,None,허남이,None,46000000.0,330000.0,None,217,02-6479-2130,https://jamsilcentralpark.com/,-6502,4천6백0만,1억7천7백0만,33만,1백0만3만,-6502,0,17A,1686289148000,127.0834603,37.5106259,None,02,8d211fa30bed4e1aae0d6d475a6a351a,12
8,9,20000358,None,None,서울특별시,성동구,천호대로416,"성동구 천호대로416 (용답동, 힐데스하임)",힐데스하임(U-삼진랜드),장한평역 힐데스하임(U-삼진랜드),None,None,170.0,5호선 장한평역 5번출구 16m,C,월세,None,제한없음,None,성부경,None,38000000.0,340000.0,None,170,010-5064-0016,없음,-6502,3천8백0만,8천0만,34만,63만,-6502,0,14,1646873528000,127.0651008,37.5609927,None,05,fc8d08def9ff40ba9785ee7be96c1acc,21
9,10,20000503,None,None,서울,종로구,숭인동 240-1,종로구 숭인동 240-1,청계로벤하임,동묘앞역 청계로벤하임,None,None,NaN,"1호선, 6호선 동묘앞역 3번출구 321m",C,월세,None,제한없음,None,청계로벤하임,None,44800000.0,340000.0,None,139,02-6273-0707,https://www.lovenheim.co.kr/,-6502,4천4백80만,1억4천4백0만,34만,85만,-6502,0,20,1690160989000,127.0183436,37.5714928,None,"01,06",d608d0950c2b4172b7bd13bad9fbb56b,21
10,11,20000419,None,None,서울,도봉구,도봉로 445,도봉구 도봉로 445,인히어쌍문,쌍문역 인히어쌍문,None,None,NaN,4호선 쌍문역 3번출구 304m,C,월세,None,제한없음,None,GHP파트너스,None,26400000.0,260000.0,None,288,02-6225-8801,http://ghp.kr/,-6502,2천6백40만,7천8백40만,26만,69만,-6502,0,"17-A2,A3",1656663972000,127.0325907,37.6458671,None,04,918d842d96654fb0869326abeb575d78,22
11,12,20000525,None,None,서울,은평구,불광동 323-21,은평구 불광동 323-21,연신내역 루체스테이션,연신내역 루체스테이션,None,None,NaN,"3호선, 6호선 연신내역 3번출구 148m",C,월세,None,제한없음,None,(주)위드웰에셋,None,40000000.0,260000.0,None,264,02-2288-0905,https://lucestation.com,-6502,4천0만,1억1천0만,26만,67만,-6502,0,17.05,1700182723000,126.9231504,37.6186684,None,"03,06",d12b3eb119184b4899ec0254d0ab4bb8,1
12,13,20000355,None,None,서울특별시,마포구,서강로75-4,"마포구 서강로75-4 (창전동, 이랜드 PEER 신촌)",이랜드신촌청년주택,광흥창역 이랜드신촌청년주택,None,None,589.0,6호선 광흥창역 1번출구 232m,C,월세,None,제한없음,None,㈜이베데스다제일호위탁관리,None,37130000.0,62000.0,None,589,02-325-9996,http://elandhome.co.kr/index.php,-6502,3천7백13만,1억9천0만95만5천0,6만2천0,47만6천0,-6502,0,17(APT형),1646872824000,126.9313209,37.5496399,None,06,b4e9c82b8b6443c7af944cf7085ecd42,18
13,14,20000359,None,None,서울특별시,종로구,난계로29길55,종로구 난계로29길55 (숭인동),동대문영하우스,동묘앞역 동대문영하우스,None,None,238.0,"1호선, 6호선 동묘앞역 3번출구 321m",C,월세,None,제한없음,None,(주)포씨즈,None,30600000.0,300000.0,None,238,02-2231-8800,없음,-6502,3천0만60만,8천7백40만,30만,76만,-6502,0,16,1646873652000,127.0201664,37.5736050,None,"01,06",c0640f0fc79549ed965e7ea6df7b9283,25
14,15,20000513,None,None,서울,중구,마른내로 159-4,중구 마른내로 159-4,166 tower,동대문역사문화공원역 166 tower,None,None,NaN,동대문역사문화공원역 5번출구 128m,C,월세,None,청년,None,이인규 외 3인,None,NaN,NaN,None,105,070-7609-0177,https://166tower.modoo.at/,-6502,-6502,-6502,-6502,-6502,-6502,0,14A,1693205538000,127.0057606,37.5648276,None,"02,04,05",087bed6fbb4d486a92ef0097e7244128,10
15,16,20000475,None,None,서울,영등포구,당산동2가 45-5,영등포구 당산동2가 45-5,포레나 당산,영등포구청역 포레나 당산,None,None,NaN,영등포구청역 6번 출구에서 146m,C,월세,None,제한없음,None,(주)당산동청년주택피에프브,None,58000000.0,310000.0,None,496,02-2633-2030,http://www.포레나당산.com,-6502,5천8백0만,1억6천6백0만,31만,71만,-6502,0,17,1668555652000,126.8939463,37.5224159,None,"02,05",dd1b3f18bc5142ab822158c66531244e,13
16,17,20000443,None,None,서울,동대문구,망우로 46,동대문구 망우로 46,회기역 하트리움,회기역 하트리움,None,None,NaN,"1호선, 경의중앙선, 경춘선, 회기역 2번출구 112m",C,월세,None,제한없음,None,(주)두진,None,54000000.0,100000.0,None,582,02-2249-9783,https://www.doojin2030.co.kr/,-6502,5천4백0만,2억2천2백0만,10만,51만,-6502,0,15A,1663129175000,127.0585367,37.5886592,None,"01,12,14",f094cf836bc846dcbc2b8ecb2c69ad37,20
17,18,20000437,None,None,서울시,은평구,대조동 2-9,은평구 대조동 2-9,불광역 역세권청년주택 호반베르디움 스테이원,불광역 호반베르디움 스테이원,None,None,NaN,"3호선, 6호선 불광역 7번출구 452m",C,월세,None,제한없음,None,대조피에프브이 주식회사,None,56000000.0,90000.0,None,977,02-355-2030,http://호반베르디움스테이원.com,-6502,5천6백0만,2억6천1백0만,9만,60만,-6502,0,17,1660193547000,126.9227960,37.6169439,None,"03,06",fbc6340187774279b9aee8b4f7c19711,21
18,19,20000436,None,None,서울,서대문구,수색로6길 8,서대문구 수색로6길 8,스타타워,가좌역 스타타워,None,None,NaN,경의중앙선 가좌역 3번출구 250m,C,월세,None,제한없음,None,가자자산,None,4400000.0,400000.0,None,124,02-2039-1143,http://www.stkaja.co.kr/,-6502,4백40만,1억3백0만,40만,89만,-6502,0,17,1660191801000,126.9135979,37.5707388,None,12,a954e5b1c7014ad4bac989f3cb2e6685,12
19,20,20000424,None,None,서울특별시,도봉구,삼양로602,"도봉구 삼양로602 (쌍문동, 에드가쌍문)",에드가쌍문,솔밭공원역 에드가쌍문,None,None,NaN,우이신설선 솔밭공원역 1번출구 84m,C,월세,None,제한없음,None,(주)도휘,None,38250000.0,350000.0,None,253,02-994-4927,https://eadgarssangmun.modoo.at/,-6502,3천8백25만,7천6백0만4만,35만,59만,-6502,0,20,1658109857000,127.0140873,37.6565799,None,16,7747fd7f0f594048b33df60ce5a4ea5f,18
20,21,20000421,None,None,서울,광진구,천호대로 517,광진구 천호대로 517,리마크빌 군자,군자역 리마크빌 군자,None,None,NaN,"5호선, 7호선 군자역 1번출구 307m",C,월세,None,제한없음,None,㈜케이리얼티임대주택제3호위,None,44000000.0,350000.0,None,299,02-552-7741,https://remarkvillgunja.com/,-6502,4천4백0만,1억1천3백0만,35만,79만,-6502,0,16,1657513068000,127.0762712,37.5589043,None,"05,07",90714d90e2f140e381768190f139243d,14
21,22,20000420,None,None,서울,송파구,석촌호수로 74,송파구 석촌호수로 74,잠실엘타워,잠실새내역 잠실엘타워,None,None,NaN,2호선 잠실새내역 3번출구 271m,C,월세,None,제한없음,None,금강실업,None,39000000.0,350000.0,None,298,02-3432-2030,www.jamsilltower.co.kr,-6502,3천9백0만,1천1백10만,35만,77만,-6502,0,16A,1656664756000,127.0855946,37.5097446,None,02,ff5956fb60da447db4bf3aaacf376710,21
22,23,20000418,None,None,서울,광진구,구의강변로 51,광진구 구의강변로 51,비바힐스 강변,강변역 비바힐스 강변,None,None,NaN,2호선 강변역 4번출구 408m,C,월세,None,제한없음,None,정지량 외 6인,None,46000000.0,370000.0,None,98,010-2314-7380,https://www.vivahillskb.co.kr/,-6502,4천6백0만,1억2백60만,37만,73만,-6502,0,15.51,1656663941000,127.0917760,37.5354322,None,02,6d66ee9b60e6474b824c2361e4c3dacd,15
23,24,20000417,None,None,서울,노원구,동일로 1000,노원구 동일로 1000,와이엔타워,태릉입구역 와이엔타워,None,None,NaN,"6호선, 7호선 태릉입구역 4번출구 166m",C,월세,None,제한없음,None,(주)태운산업개발,None,32000000.0,300000.0,None,270,02-449-7425,https://yntower.modoo.at/,-6502,3천2백0만,9천9백0만,30만,81만,-6502,0,16.3,1656663879000,127.0755262,37.6194890,None,"06,07",356f0ab9e20e42f88b4c06e1c18e46ad,11
24,25,20000416,None,None,서울,중랑구,공릉로2길 8-4,중랑구 공릉로2길 8-4,칼튼테라스,먹골역 칼튼테라스,None,None,NaN,7호선 먹골역 1번출구 39m,C,월세,None,제한없음,None,더블라썸묵동,None,27790000.0,250000.0,None,235,02-971-1527,https://carltonterrace.modoo.at,-6502,2천7백79만,7천6백36만,25만,51만,-6502,0,16,1656663844000,127.0782455,37.6118425,None,07,5dedab2401e6413aaa8561140e53210c,17
25,26,20000415,None,None,서울,강서구,강서로56길 44,강서구 강서로56길 44,엘크루 발산,발산역 엘크루,None,None,NaN,5호선 발산역 3번출구 286m,C,월세,None,제한없음,None,펠리즈타워,None,38000000.0,220000.0,None,252,02-6735-1560,https://youngtower.modoo.at/,-6502,3천8백0만,9천6백0만,22만,58만,-6502,0,A-15.33,1656663792000,126.8411060,37.5591863,None,05,dab03b7f6cf14fd9af259a623a91f6d4,10
26,27,20000414,None,None,서울,광진구,구의강변로 53,광진구 구의강변로 53,옥산그린타워,강변역 옥산그린타워,None,None,NaN,2호선 강변역 4번출구 455m,C,월세,None,제한없음,None,이강옥,None,28240000.0,190000.0,None,74,010-5221-8030,-,-6502,2천8백24만,1억5백0만9만,19만,59만,-6502,0,16,1656663649000,127.0919002,37.5357340,None,02,57468e62f133475ca50c180f4ba7204a,10
27,28,20000413,None,None,서울,영등포구,도신로 59,영등포구 도신로 59,도림브라보,신도림역 도림브라보,None,None,NaN,"1호선, 2호선 신도림역 2번출구 908m(도림사거리역 예정)",C,월세,None,제한없음,None,김병준,None,35000000.0,190000.0,None,99,02-833-8114,https://dorimbravo.modoo.at/,-6502,3천5백0만,1억2천2백0만,19만,67만,-6502,0,16.12,1656663333000,126.8992534,37.5060269,None,"01,02",e18bb5a6b288406cb40c5d239abc2e09,12
28,29,20000412,None,None,서울,강서구,화곡로 146,강서구 화곡로 146,포르투나 블루,화곡역 포르투나 블루,None,None,NaN,5호선 화곡역 6번출구 211m,C,월세,None,제한없음,None,권기범 외 3인,None,50000000.0,80000.0,None,82,010-8436-8982,https://fortunablue.modoo.at,-6502,5천0만,2억,8만,71만,-6502,0,20.08,1656655830000,126.8379477,37.5407078,None,05,342da583357244c199518640545aca4c,13
29,30,20000406,None,None,서울,용산구,원효로97길 15,용산구 원효로97길 15,용산 원효 루미니,남영역 용산 원효 루미니,None,None,NaN,"1호선, 4호선 남영역 1번출구 268m",C,월세,None,제한없음,None,롯데건설,None,50340000.0,240000.0,None,751,02-821-4013,https://www.elyes.co.kr,-6502,5천0만34만,1억8천4백80만,24만,93만,-6502,0,15A,1653282737000,126.9693501,37.5413341,None,01,926a7b6e2e8b4a2f9380541b5ecaa41c,31
30,31,20000386,None,None,서울,관악구,남부순환로224길 25,관악구 남부순환로224길 25,BX201,서울대입구역 BX201,None,None,NaN,2호선 서울대입구역 1번출구 136m,C,월세,None,제한없음,None,BX201,None,24000000.0,290000.0,None,201,02-883-3065,www.bx201.co.kr,-6502,2천4백0만,1억3백0만,29만,91만,-6502,0,15,1652145926000,126.9533484,37.4796946,None,02,1c91030026d74a9a8bbf703e9f87c72b,43
31,32,20000371,None,None,서울,강서구,강서로 231,강서구 강서로 231,우장산 해링턴타워,우장산역 해링턴타워,None,None,429.0,5호선 우장산역 3번출구 232m,C,월세,None,제한없음,None,(주)선우,None,3680000.0,250000.0,None,429,010-2545-4000,https://ujs2030.co.kr/,-6502,3백68만,1억4백0만,25만,65만,-6502,0,17A,1649223633000,126.8361212,37.5462462,None,05,6ec97082c69b42d995201e3907c54924,17
32,33,20000370,None,None,서울,강남구,봉은사로 125,강남구 봉은사로 125,리스트강남,신논현역 리스트 강남,None,None,NaN,"9호선, 신분당선 신논현역 3번출구 258m",C,월세,None,제한없음,None,(주)브이홀딩스,None,41570000.0,380000.0,None,297,02-542-6114,http://www.listgangnam.co.kr/,-6502,4천1백57만,1억4천7백44만,38만,95만,-6502,0,14A,1649149044000,127.0274260,37.5057599,None,"09,11",63bbf5888a4245dcb58d6c9be60d93e1,24
33,34,20000365,None,None,서울특별시,마포구,토정로131,"마포구 토정로131 (상수동, 상수크리원)",홍대 크리원,상수역 홍대 크리원,None,None,95.0,6호선 상수역 3번출구 473m,C,월세,None,제한없음,None,무궁화신탁,None,17000000.0,470000.0,None,95,02-6052-5335,https://www.creaone.kr/kr/index.php,-6502,1천7백0만,1억2천9백0만,47만,99만,-6502,0,17,1646874738000,126.9254097,37.5454085,None,06,dcefca12204c4200ad7ac9151f9cf6f3,18
34,35,20000364,None,None,서울특별시,강동구,천호대로989,"강동구 천호대로989 (천호동, 천호역 한강 청년주택)",천호역 한강 리슈빌,천호역 한강리슈빌,None,None,223.0,"5호선, 8호선 천호역 1번출구 59m",C,월세,None,제한없음,None,알이비에셋,None,11050000.0,270000.0,None,223,02-6472-3902,https://천호역세권청년주택.com,-6502,1천1백0만5만,7천9백81만,27만,71만,-6502,0,14A,1646874635000,127.1223994,37.5394615,None,"05,08",6eea594d869648f4ad5d95b83f0f2d96,26
35,36,20000363,None,None,서울,서초구,반포대로27길 13,서초구 반포대로27길 13,서초꽃마을,서초역 서초꽃마을,None,None,280.0,2호선 서초역 3번출구 218m,C,월세,None,제한없음,None,서초꽃마을 1502,None,24750000.0,80000.0,None,280,02-6241-1502,https://seocho1502.modoo.at/,-6502,2천4백75만,1억3백0만,8만,79만,-6502,0,16.63,1646874537000,127.0076047,37.4896931,None,02,822b6fcd6e08400cb8e2df91cf054e70,12
36,37,20000362,None,None,서울특별시,용산구,백범로99길40,"용산구 백범로99길40 (한강로2가, 용산 베르디움 프렌즈)",용산 베르디움,삼각지역 용산 베르디움 프렌즈,None,None,1086.0,"4호선, 6호선 삼각지역 8번출구 166m",C,월세,None,제한없음,None,(주)용산대한뉴스테이위탁관,None,22840000.0,80000.0,None,1086,02-3785-3344,http://www.ys-vertium-friends.co.kr/main/index...,-6502,2천2백84만,1억9천7백0만7만,8만,65만,-6502,0,19,1646874385000,126.9715459,37.5355646,None,"04,06",6d4122b0a0fc4913be49a1665de8b68d,35
37,38,20000361,None,None,서울특별시,동작구,노량진로8길55,"동작구 노량진로8길55 (노량진동, 더 클래식 동작)",더클래식 동작,노량진역 더클래식동작,None,None,272.0,"1호선, 9호선 노량진역 6번출구 230m",C,월세,None,제한없음,None,더클래식동작,None,33040000.0,100000.0,None,272,02-823-3300,https://theclassic2030.modoo.at/,-6502,3천3백0만4만,1억1천4백42만,10만,72만,-6502,0,15.73,1646874115000,126.9385648,37.5123712,None,"01,09",4445b24cf3514c398b9bdad8cf6d1948,19
38,39,20000360,None,None,서울특별시,강서구,공항대로59가길14,"강서구 공항대로59가길14 (등촌동, 아임2030 등촌역)",아임2030,등촌역 아임2030,None,None,285.0,9호선 등촌역 1번출구 143m,C,월세,None,제한없음,None,대호주택건설,None,18630000.0,60000.0,None,285,02-3663-6000,https://im2030.modoo.at,-6502,1천8백63만,6천2백0만,6만,44만,-6502,0,15A,1646873822000,126.8645879,37.5517668,None,09,6f0be5cf315a47b1ac7b23fa141326f0,23
39,40,20000357,None,None,서울특별시,동대문구,망우로21나길6,"동대문구 망우로21나길6 (휘경동, 휘경 제이스카이시티)",휘경제이스카이시티,회기역 휘경제이스카이시티,None,None,99.0,"1호선, 경의중앙선, 경춘선, 회기역 2번출구 229m",C,월세,None,제한없음,None,(주)휴먼타운,None,19290000.0,70000.0,None,99,02-3390-4700,https://hkjskycity.modoo.at/,-6502,1천9백29만,7천4백0만8만,7만,67만,-6502,0,14D,1646873307000,127.0607127,37.5905010,None,"01,12,14",0799e07f1c4744e598376fc8ba0af163,31
40,41,20000356,None,None,서울특별시,강서구,강서로145,"강서구 강서로145 (화곡동, 보눔 하우스 화곡)",보눔 하우스 화곡,화곡역 보눔하우스 화곡,None,None,0.0,5호선 화곡역 5번출구 176m,C,월세,None,제한없음,None,장의종,None,14960000.0,50000.0,None,57,010-8730-8680,https://bonumhaus2030.modoo.at/,-6502,1천4백96만,6천0만4만,5만,45만,-6502,0,14.35A,1646873069000,126.8414159,37.5399014,None,05,049330c9a9c34446ac8562009866cfea,16
41,42,20000354,None,None,서울특별시,강서구,공항대로543,"강서구 공항대로543 (염창동, 센터스퀘어)",센터스퀘어 등촌,등촌역 센터스퀘어 등촌,None,None,500.0,9호선 등촌역 2번출구 105m,C,월세,None,제한없음,None,멀티에셋등촌역청년주택,None,29040000.0,240000.0,None,500,02-3662-1410,https://centersquare.modoo.at/,-6502,2천9백0만4만,9천6백80만,24만,71만,-6502,0,18,1646872369000,126.8664122,37.5507389,None,09,9281e51682e54f38a7aceb5763a8e82d,20
42,43,20000353,None,None,서울특별시,마포구,양화로72,마포구 양화로72 (서교동),서교동 효성 해링턴 타워,합정역 서교 효성 해링턴타워,None,None,913.0,"2호선, 6호선 합정역 3번출구 59m",C,월세,None,제한없음,None,멀티에셋합정역청년주택,None,61200000.0,370000.0,None,913,02-335-1800,-,-6502,6천1백20만,1억3천7백60만,37만,1백12만,-6502,0,17,1646871885000,126.9167159,37.5508021,None,"02,06",ec67828a1c43458080f551add34f166c,20
43,44,20000352,None,None,서울특별시,서대문구,경기대로22,서대문구 경기대로22 (충정로3가),어바니엘 위드 더 스타일 충정로,충정로역 어바니엘 위드 더 스타일 충정로,None,None,499.0,"2호선, 5호선 중정로역 8번 출구 70m",C,월세,None,제한없음,None,(주) 롯데건설,None,36400000.0,290000.0,None,499,02-2653-2800,https://www.elyes.co.kr/main/stayView.do?pid=10,-6502,3천6백40만,1억1천2백80만,29만,78만,-6502,0,15,1646871454000,126.9624299,37.5611380,None,"02,05",f0e08a041a944fc0bf2e0908723ca320,31
44,45,20000479,None,None,서울,서초구,남부순환로 2567,서초구 남부순환로 2567,"1365-8번지, 코네스트",양재역 CONEST,None,None,NaN,3호선 양재역 1번 출구에서 169m,C,월세,None,제한없음,None,청년당당,None,68000000.0,290000.0,None,379,02-583-5250,http://www.conest.co.kr/,-6502,6천8백0만,1억5천9백0만,29만,81만,-6502,0,17A,1673850129000,127.0312461,37.4845510,None,"03,11",e929d0300d9d48d3b714e2ee1c0f1bbb,19
45,46,20000480,None,None,서울,강남구,논현로 423,강남구 논현로 423,더원역삼,역삼역 더원역삼,None,None,NaN,2호선 역삼역 2번출구 365m,C,월세,None,제한없음,None,에스엠티컴퍼니,None,4900000.0,410000.0,None,78,031-797-2909,https://www.theoneys.co.kr/,-6502,4백90만,1억2천3백0만,41만,86만,-6502,0,16,1673852091000,127.0379373,37.4978485,None,02,8dd593027bd84c9b8a74f6079548925e,19
46,47,20000482,None,None,서울,광진구,구의강변로 57,광진구 구의강변로 57,센텀힐스한강,강변역 센텀힐스한강,None,None,NaN,2호선 강변역 4번출구 398m,C,월세,None,제한없음,None,양석영 외 1인,None,44000000.0,340000.0,None,70,02-456-0066,http://www.centumhills.co.kr/,-6502,4천4백0만,8천9백0만,34만,71만,-6502,0,16A,1674803214000,127.0920590,37.5359246,None,02,685e1d2231764e87bc9286eaf0171225,14
47,48,20000484,None,None,서울,강남구,논현동 278-4,강남구 논현동 278-4,선정릉역 모아엘가 퍼스트홈,선정릉역 모아엘가 퍼스트홈,None,None,NaN,"9호선, 수인분당선 1번출구 133m",C,월세,None,제한없음,None,(주)삼조디앤씨,None,31620000.0,240000.0,None,283,1522-2067,https://first-home.co.kr/,-6502,3천1백62만,1억5백48만,24만,68만,-6502,0,14A,1676009453000,127.0430717,37.5105184,None,"09,10",7a66d47aece6435b83b9eb103a8a90e3,28
48,49,20000496,None,None,서울,관악구,남부순환로180길 6,관악구 남부순환로180길 6,최강타워,신림역 최강타워,None,None,NaN,"2호선, 신림선 신림역 1번출구 43m",C,월세,None,제한없음,None,(주)신림리더스하우징,None,37000000.0,340000.0,None,299,1899-8733,https://www.최강타워.com,-6502,3천7백0만,9천8백0만,34만,85만,-6502,0,17,1686290938000,126.9308781,37.4840188,None,02,0eb4964e987a41fabdf93e1043501173,16
49,50,20000501,None,None,서울,영등포구,신길동 173-6,영등포구 신길동 173-6,신길역 준타워,신길역 준타워,None,None,NaN,"1호선, 5호선 신길역 1번출구 345m",C,월세,None,제한없음,None,(주)제이케이스타,None,37000000.0,290000.0,None,162,02-848-0888,https://juntower.co.kr,-6502,3천7백0만,1억5천2백0만,29만,79만,-6502,0,16A,1689569636000,126.9167395,37.5149414,None,"01,05",09cabc273c47471783977c1801526ed0,11

In [58]:
ansim_df.head(1)

,rnum,homeCode,mainImgAtchFileId,mainImgAtchFileSeq,adresSi,adresGu,adresRo,adres,adresDetail,homeName,totArea,totFloor,totPeople,optionSubway,presale,presaleNm,movinTerms,movinHoman,houseSupplyNm,managerComp,moneyDeposit,moneyDepositLow,moneyRentalLow,tradPrice,scaleTot,managerPhone,homepage,fnMoneyDeposit,fnMoneyDepositLow,fnMoneyDepositHigh,fnMoneyRentalLow,fnMoneyRentalHigh,fnTradPrice,statusCnt,roomTotArea,regDate,xpos,ypos,houseStrut,subwayLineCd,fileId,fileSn
0,1,20000540,None,None,서울,은평구,갈현동 456-25,은평구 갈현동 456-25,THE STUDIO 163,연신내역 THE STUDIO 163,None,None,NaN,"3호선, 6호선 연신내역 5번출구 236m",C,월세,None,제한없음,None,THE STUDIO 163,None,40000000.0,290000.0,None,163,02-564-4866,http://www.thestudio163.co.kr,-6502,4천0만,8천6백0만,29만,53만,-6502,0,17A,1712125695000,126.9190859,37.6179079,None,"03,06",16d932a39bb04b9cae0ca3653aa07108,1

In [59]:
ansim_df.columns

Index(['rnum', 'homeCode', 'mainImgAtchFileId', 'mainImgAtchFileSeq',
       'adresSi', 'adresGu', 'adresRo', 'adres', 'adresDetail', 'homeName',
       'totArea', 'totFloor', 'totPeople', 'optionSubway', 'presale',
       'presaleNm', 'movinTerms', 'movinHoman', 'houseSupplyNm', 'managerComp',
       'moneyDeposit', 'moneyDepositLow', 'moneyRentalLow', 'tradPrice',
       'scaleTot', 'managerPhone', 'homepage', 'fnMoneyDeposit',
       'fnMoneyDepositLow', 'fnMoneyDepositHigh', 'fnMoneyRentalLow',
       'fnMoneyRentalHigh', 'fnTradPrice', 'statusCnt', 'roomTotArea',
       'regDate', 'xpos', 'ypos', 'houseStrut', 'subwayLineCd', 'fileId',
       'fileSn'],
      dtype='object')

In [60]:
select_col = ['adresGu','adresRo', 'scaleTot','roomTotArea','moneyRentalLow','moneyDepositLow',
       'fnMoneyDepositLow', 'fnMoneyDepositHigh', 'fnMoneyRentalLow',
       'fnMoneyRentalHigh']

In [61]:
ansim2 = ansim_df[select_col]

In [62]:
ansim2

,adresGu,adresRo,scaleTot,roomTotArea,moneyRentalLow,moneyDepositLow,fnMoneyDepositLow,fnMoneyDepositHigh,fnMoneyRentalLow,fnMoneyRentalHigh
0,은평구,갈현동 456-25,163,17A,290000.0,40000000.0,4천0만,8천6백0만,29만,53만
1,중랑구,상봉동 118-8,299,18.03(18A),280000.0,43000000.0,4천3백0만,1억3천2백0만,28만,76만
2,중랑구,봉우재로 111,83,17.02,300000.0,36000000.0,3천6백0만,7천6백0만,30만,60만
3,은평구,서오릉로 165,238,17A,290000.0,36000000.0,3천6백0만,9천1백0만,29만,67만
4,동작구,노량진동 54-1,299,17.78C,310000.0,45000000.0,4천5백0만,1억9천1백0만,31만,1백0만6만
5,동작구,대방동 403-14,110,18A,240000.0,34000000.0,3천4백0만,1억2천8백0만,24만,73만
6,송파구,문정동 55-6,438,16A,360000.0,42000000.0,4천2백0만,1억1천6백0만,36만,86만
7,송파구,잠실동 187-10,217,17A,330000.0,46000000.0,4천6백0만,1억7천7백0만,33만,1백0만3만
8,성동구,천호대로416,170,14,340000.0,38000000.0,3천8백0만,8천0만,34만,63만
9,종로구,숭인동 240-1,139,20,340000.0,44800000.0,4천4백80만,1억4천4백0만,34만,85만
10,도봉구,도봉로 445,288,"17-A2,A3",260000.0,26400000.0,2천6백40만,7천8백40만,26만,69만
11,은평구,불광동 323-21,264,17.05,260000.0,40000000.0,4천0만,1억1천0만,26만,67만
12,마포구,서강로75-4,589,17(APT형),62000.0,37130000.0,3천7백13만,1억9천0만95만5천0,6만2천0,47만6천0
13,종로구,난계로29길55,238,16,300000.0,30600000.0,3천0만60만,8천7백40만,30만,76만
14,중구,마른내로 159-4,105,14A,NaN,NaN,-6502,-6502,-6502,-6502
15,영등포구,당산동2가 45-5,496,17,310000.0,58000000.0,5천8백0만,1억6천6백0만,31만,71만
16,동대문구,망우로 46,582,15A,100000.0,54000000.0,5천4백0만,2억2천2백0만,10만,51만
17,은평구,대조동 2-9,977,17,90000.0,56000000.0,5천6백0만,2억6천1백0만,9만,60만
18,서대문구,수색로6길 8,124,17,400000.0,4400000.0,4백40만,1억3백0만,40만,89만
19,도봉구,삼양로602,253,20,350000.0,38250000.0,3천8백25만,7천6백0만4만,35만,59만
20,광진구,천호대로 517,299,16,350000.0,44000000.0,4천4백0만,1억1천3백0만,35만,79만
21,송파구,석촌호수로 74,298,16A,350000.0,39000000.0,3천9백0만,1천1백10만,35만,77만
22,광진구,구의강변로 51,98,15.51,370000.0,46000000.0,4천6백0만,1억2백60만,37만,73만
23,노원구,동일로 1000,270,16.3,300000.0,32000000.0,3천2백0만,9천9백0만,30만,81만
24,중랑구,공릉로2길 8-4,235,16,250000.0,27790000.0,2천7백79만,7천6백36만,25만,51만
25,강서구,강서로56길 44,252,A-15.33,220000.0,38000000.0,3천8백0만,9천6백0만,22만,58만
26,광진구,구의강변로 53,74,16,190000.0,28240000.0,2천8백24만,1억5백0만9만,19만,59만
27,영등포구,도신로 59,99,16.12,190000.0,35000000.0,3천5백0만,1억2천2백0만,19만,67만
28,강서구,화곡로 146,82,20.08,80000.0,50000000.0,5천0만,2억,8만,71만
29,용산구,원효로97길 15,751,15A,240000.0,50340000.0,5천0만34만,1억8천4백80만,24만,93만
30,관악구,남부순환로224길 25,201,15,290000.0,24000000.0,2천4백0만,1억3백0만,29만,91만
31,강서구,강서로 231,429,17A,250000.0,3680000.0,3백68만,1억4백0만,25만,65만
32,강남구,봉은사로 125,297,14A,380000.0,41570000.0,4천1백57만,1억4천7백44만,38만,95만
33,마포구,토정로131,95,17,470000.0,17000000.0,1천7백0만,1억2천9백0만,47만,99만
34,강동구,천호대로989,223,14A,270000.0,11050000.0,1천1백0만5만,7천9백81만,27만,71만
35,서초구,반포대로27길 13,280,16.63,80000.0,24750000.0,2천4백75만,1억3백0만,8만,79만
36,용산구,백범로99길40,1086,19,80000.0,22840000.0,2천2백84만,1억9천7백0만7만,8만,65만
37,동작구,노량진로8길55,272,15.73,100000.0,33040000.0,3천3백0만4만,1억1천4백42만,10만,72만
38,강서구,공항대로59가길14,285,15A,60000.0,18630000.0,1천8백63만,6천2백0만,6만,44만
39,동대문구,망우로21나길6,99,14D,70000.0,19290000.0,1천9백29만,7천4백0만8만,7만,67만
40,강서구,강서로145,57,14.35A,50000.0,14960000.0,1천4백96만,6천0만4만,5만,45만
41,강서구,공항대로543,500,18,240000.0,29040000.0,2천9백0만4만,9천6백80만,24만,71만
42,마포구,양화로72,913,17,370000.0,61200000.0,6천1백20만,1억3천7백60만,37만,1백12만
43,서대문구,경기대로22,499,15,290000.0,36400000.0,3천6백40만,1억1천2백80만,29만,78만
44,서초구,남부순환로 2567,379,17A,290000.0,68000000.0,6천8백0만,1억5천9백0만,29만,81만
45,강남구,논현로 423,78,16,410000.0,4900000.0,4백90만,1억2천3백0만,41만,86만
46,광진구,구의강변로 57,70,16A,340000.0,44000000.0,4천4백0만,8천9백0만,34만,71만
47,강남구,논현동 278-4,283,14A,240000.0,31620000.0,3천1백62만,1억5백48만,24만,68만
48,관악구,남부순환로180길 6,299,17,340000.0,37000000.0,3천7백0만,9천8백0만,34만,85만
49,영등포구,신길동 173-6,162,16A,290000.0,37000000.0,3천7백0만,1억5천2백0만,29만,79만

In [63]:
a = ansim2['roomTotArea'].tolist()

In [64]:
a

['17A',
 '18.03(18A)',
 '17.02',
 '17A',
 '17.78C',
 '18A',
 '16A',
 '17A',
 '14',
 '20',
 '17-A2,A3',
 '17.05',
 '17(APT형)',
 '16',
 '14A',
 '17',
 '15A',
 '17',
 '17',
 '20',
 '16',
 '16A',
 '15.51',
 '16.3',
 '16',
 'A-15.33',
 '16',
 '16.12',
 '20.08',
 '15A',
 '15',
 '17A',
 '14A',
 '17',
 '14A',
 '16.63',
 '19',
 '15.73',
 '15A',
 '14D',
 '14.35A',
 '18',
 '17',
 '15',
 '17A',
 '16',
 '16A',
 '14A',
 '17',
 '16A']

In [65]:
import re

# 주어진 리스트
data_list = a

# 알파벳만을 제거하는 정규식 패턴
pattern = re.compile(r'[A-Za-z]+')
# 괄호와 괄호 안에 있는 내용을 지우는 정규식 패턴
pattern2 = re.compile(r'\(.*?\)')

result_list = [re.sub(pattern, '', value) for value in data_list]
# 리스트 컴프리헨션을 사용하여 각 값에서 괄호와 그 안에 있는 내용을 제거
result_list = [re.sub(pattern2, '', value) for value in result_list]

# 결과 출력
print(result_list)

['17', '18.03', '17.02', '17', '17.78', '18', '16', '17', '14', '20', '17-2,3', '17.05', '17', '16', '14', '17', '15', '17', '17', '20', '16', '16', '15.51', '16.3', '16', '-15.33', '16', '16.12', '20.08', '15', '15', '17', '14', '17', '14', '16.63', '19', '15.73', '15', '14', '14.35', '18', '17', '15', '17', '16', '16', '14', '17', '16']

In [66]:
print(result_list.index('17-2,3'))
print(result_list.index('-15.33'))

10
25

In [67]:
result_list[10] = 17
result_list[25] = 15.33

In [68]:
ansim2['roomTotArea'] = result_list

/tmp/ipykernel_16746/3806975381.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ansim2['roomTotArea'] = result_list

In [69]:
ansim2['roomTotArea'] = ansim2['roomTotArea'].astype(float)

/tmp/ipykernel_16746/2776133230.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ansim2['roomTotArea'] = ansim2['roomTotArea'].astype(float)

In [70]:
ansim2

,adresGu,adresRo,scaleTot,roomTotArea,moneyRentalLow,moneyDepositLow,fnMoneyDepositLow,fnMoneyDepositHigh,fnMoneyRentalLow,fnMoneyRentalHigh
0,은평구,갈현동 456-25,163,17.00,290000.0,40000000.0,4천0만,8천6백0만,29만,53만
1,중랑구,상봉동 118-8,299,18.03,280000.0,43000000.0,4천3백0만,1억3천2백0만,28만,76만
2,중랑구,봉우재로 111,83,17.02,300000.0,36000000.0,3천6백0만,7천6백0만,30만,60만
3,은평구,서오릉로 165,238,17.00,290000.0,36000000.0,3천6백0만,9천1백0만,29만,67만
4,동작구,노량진동 54-1,299,17.78,310000.0,45000000.0,4천5백0만,1억9천1백0만,31만,1백0만6만
5,동작구,대방동 403-14,110,18.00,240000.0,34000000.0,3천4백0만,1억2천8백0만,24만,73만
6,송파구,문정동 55-6,438,16.00,360000.0,42000000.0,4천2백0만,1억1천6백0만,36만,86만
7,송파구,잠실동 187-10,217,17.00,330000.0,46000000.0,4천6백0만,1억7천7백0만,33만,1백0만3만
8,성동구,천호대로416,170,14.00,340000.0,38000000.0,3천8백0만,8천0만,34만,63만
9,종로구,숭인동 240-1,139,20.00,340000.0,44800000.0,4천4백80만,1억4천4백0만,34만,85만
10,도봉구,도봉로 445,288,17.00,260000.0,26400000.0,2천6백40만,7천8백40만,26만,69만
11,은평구,불광동 323-21,264,17.05,260000.0,40000000.0,4천0만,1억1천0만,26만,67만
12,마포구,서강로75-4,589,17.00,62000.0,37130000.0,3천7백13만,1억9천0만95만5천0,6만2천0,47만6천0
13,종로구,난계로29길55,238,16.00,300000.0,30600000.0,3천0만60만,8천7백40만,30만,76만
14,중구,마른내로 159-4,105,14.00,NaN,NaN,-6502,-6502,-6502,-6502
15,영등포구,당산동2가 45-5,496,17.00,310000.0,58000000.0,5천8백0만,1억6천6백0만,31만,71만
16,동대문구,망우로 46,582,15.00,100000.0,54000000.0,5천4백0만,2억2천2백0만,10만,51만
17,은평구,대조동 2-9,977,17.00,90000.0,56000000.0,5천6백0만,2억6천1백0만,9만,60만
18,서대문구,수색로6길 8,124,17.00,400000.0,4400000.0,4백40만,1억3백0만,40만,89만
19,도봉구,삼양로602,253,20.00,350000.0,38250000.0,3천8백25만,7천6백0만4만,35만,59만
20,광진구,천호대로 517,299,16.00,350000.0,44000000.0,4천4백0만,1억1천3백0만,35만,79만
21,송파구,석촌호수로 74,298,16.00,350000.0,39000000.0,3천9백0만,1천1백10만,35만,77만
22,광진구,구의강변로 51,98,15.51,370000.0,46000000.0,4천6백0만,1억2백60만,37만,73만
23,노원구,동일로 1000,270,16.30,300000.0,32000000.0,3천2백0만,9천9백0만,30만,81만
24,중랑구,공릉로2길 8-4,235,16.00,250000.0,27790000.0,2천7백79만,7천6백36만,25만,51만
25,강서구,강서로56길 44,252,15.33,220000.0,38000000.0,3천8백0만,9천6백0만,22만,58만
26,광진구,구의강변로 53,74,16.00,190000.0,28240000.0,2천8백24만,1억5백0만9만,19만,59만
27,영등포구,도신로 59,99,16.12,190000.0,35000000.0,3천5백0만,1억2천2백0만,19만,67만
28,강서구,화곡로 146,82,20.08,80000.0,50000000.0,5천0만,2억,8만,71만
29,용산구,원효로97길 15,751,15.00,240000.0,50340000.0,5천0만34만,1억8천4백80만,24만,93만
30,관악구,남부순환로224길 25,201,15.00,290000.0,24000000.0,2천4백0만,1억3백0만,29만,91만
31,강서구,강서로 231,429,17.00,250000.0,3680000.0,3백68만,1억4백0만,25만,65만
32,강남구,봉은사로 125,297,14.00,380000.0,41570000.0,4천1백57만,1억4천7백44만,38만,95만
33,마포구,토정로131,95,17.00,470000.0,17000000.0,1천7백0만,1억2천9백0만,47만,99만
34,강동구,천호대로989,223,14.00,270000.0,11050000.0,1천1백0만5만,7천9백81만,27만,71만
35,서초구,반포대로27길 13,280,16.63,80000.0,24750000.0,2천4백75만,1억3백0만,8만,79만
36,용산구,백범로99길40,1086,19.00,80000.0,22840000.0,2천2백84만,1억9천7백0만7만,8만,65만
37,동작구,노량진로8길55,272,15.73,100000.0,33040000.0,3천3백0만4만,1억1천4백42만,10만,72만
38,강서구,공항대로59가길14,285,15.00,60000.0,18630000.0,1천8백63만,6천2백0만,6만,44만
39,동대문구,망우로21나길6,99,14.00,70000.0,19290000.0,1천9백29만,7천4백0만8만,7만,67만
40,강서구,강서로145,57,14.35,50000.0,14960000.0,1천4백96만,6천0만4만,5만,45만
41,강서구,공항대로543,500,18.00,240000.0,29040000.0,2천9백0만4만,9천6백80만,24만,71만
42,마포구,양화로72,913,17.00,370000.0,61200000.0,6천1백20만,1억3천7백60만,37만,1백12만
43,서대문구,경기대로22,499,15.00,290000.0,36400000.0,3천6백40만,1억1천2백80만,29만,78만
44,서초구,남부순환로 2567,379,17.00,290000.0,68000000.0,6천8백0만,1억5천9백0만,29만,81만
45,강남구,논현로 423,78,16.00,410000.0,4900000.0,4백90만,1억2천3백0만,41만,86만
46,광진구,구의강변로 57,70,16.00,340000.0,44000000.0,4천4백0만,8천9백0만,34만,71만
47,강남구,논현동 278-4,283,14.00,240000.0,31620000.0,3천1백62만,1억5백48만,24만,68만
48,관악구,남부순환로180길 6,299,17.00,340000.0,37000000.0,3천7백0만,9천8백0만,34만,85만
49,영등포구,신길동 173-6,162,16.00,290000.0,37000000.0,3천7백0만,1억5천2백0만,29만,79만

In [71]:
ansim2[ansim2['moneyDepositLow'].isnull()]

,adresGu,adresRo,scaleTot,roomTotArea,moneyRentalLow,moneyDepositLow,fnMoneyDepositLow,fnMoneyDepositHigh,fnMoneyRentalLow,fnMoneyRentalHigh
14,중구,마른내로 159-4,105,14.0,NaN,NaN,-6502,-6502,-6502,-6502

In [72]:
ansim2.drop(14, axis=0,inplace = True)

/tmp/ipykernel_16746/3349873651.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ansim2.drop(14, axis=0,inplace = True)

In [73]:
ansim2

,adresGu,adresRo,scaleTot,roomTotArea,moneyRentalLow,moneyDepositLow,fnMoneyDepositLow,fnMoneyDepositHigh,fnMoneyRentalLow,fnMoneyRentalHigh
0,은평구,갈현동 456-25,163,17.00,290000.0,40000000.0,4천0만,8천6백0만,29만,53만
1,중랑구,상봉동 118-8,299,18.03,280000.0,43000000.0,4천3백0만,1억3천2백0만,28만,76만
2,중랑구,봉우재로 111,83,17.02,300000.0,36000000.0,3천6백0만,7천6백0만,30만,60만
3,은평구,서오릉로 165,238,17.00,290000.0,36000000.0,3천6백0만,9천1백0만,29만,67만
4,동작구,노량진동 54-1,299,17.78,310000.0,45000000.0,4천5백0만,1억9천1백0만,31만,1백0만6만
5,동작구,대방동 403-14,110,18.00,240000.0,34000000.0,3천4백0만,1억2천8백0만,24만,73만
6,송파구,문정동 55-6,438,16.00,360000.0,42000000.0,4천2백0만,1억1천6백0만,36만,86만
7,송파구,잠실동 187-10,217,17.00,330000.0,46000000.0,4천6백0만,1억7천7백0만,33만,1백0만3만
8,성동구,천호대로416,170,14.00,340000.0,38000000.0,3천8백0만,8천0만,34만,63만
9,종로구,숭인동 240-1,139,20.00,340000.0,44800000.0,4천4백80만,1억4천4백0만,34만,85만
10,도봉구,도봉로 445,288,17.00,260000.0,26400000.0,2천6백40만,7천8백40만,26만,69만
11,은평구,불광동 323-21,264,17.05,260000.0,40000000.0,4천0만,1억1천0만,26만,67만
12,마포구,서강로75-4,589,17.00,62000.0,37130000.0,3천7백13만,1억9천0만95만5천0,6만2천0,47만6천0
13,종로구,난계로29길55,238,16.00,300000.0,30600000.0,3천0만60만,8천7백40만,30만,76만
15,영등포구,당산동2가 45-5,496,17.00,310000.0,58000000.0,5천8백0만,1억6천6백0만,31만,71만
16,동대문구,망우로 46,582,15.00,100000.0,54000000.0,5천4백0만,2억2천2백0만,10만,51만
17,은평구,대조동 2-9,977,17.00,90000.0,56000000.0,5천6백0만,2억6천1백0만,9만,60만
18,서대문구,수색로6길 8,124,17.00,400000.0,4400000.0,4백40만,1억3백0만,40만,89만
19,도봉구,삼양로602,253,20.00,350000.0,38250000.0,3천8백25만,7천6백0만4만,35만,59만
20,광진구,천호대로 517,299,16.00,350000.0,44000000.0,4천4백0만,1억1천3백0만,35만,79만
21,송파구,석촌호수로 74,298,16.00,350000.0,39000000.0,3천9백0만,1천1백10만,35만,77만
22,광진구,구의강변로 51,98,15.51,370000.0,46000000.0,4천6백0만,1억2백60만,37만,73만
23,노원구,동일로 1000,270,16.30,300000.0,32000000.0,3천2백0만,9천9백0만,30만,81만
24,중랑구,공릉로2길 8-4,235,16.00,250000.0,27790000.0,2천7백79만,7천6백36만,25만,51만
25,강서구,강서로56길 44,252,15.33,220000.0,38000000.0,3천8백0만,9천6백0만,22만,58만
26,광진구,구의강변로 53,74,16.00,190000.0,28240000.0,2천8백24만,1억5백0만9만,19만,59만
27,영등포구,도신로 59,99,16.12,190000.0,35000000.0,3천5백0만,1억2천2백0만,19만,67만
28,강서구,화곡로 146,82,20.08,80000.0,50000000.0,5천0만,2억,8만,71만
29,용산구,원효로97길 15,751,15.00,240000.0,50340000.0,5천0만34만,1억8천4백80만,24만,93만
30,관악구,남부순환로224길 25,201,15.00,290000.0,24000000.0,2천4백0만,1억3백0만,29만,91만
31,강서구,강서로 231,429,17.00,250000.0,3680000.0,3백68만,1억4백0만,25만,65만
32,강남구,봉은사로 125,297,14.00,380000.0,41570000.0,4천1백57만,1억4천7백44만,38만,95만
33,마포구,토정로131,95,17.00,470000.0,17000000.0,1천7백0만,1억2천9백0만,47만,99만
34,강동구,천호대로989,223,14.00,270000.0,11050000.0,1천1백0만5만,7천9백81만,27만,71만
35,서초구,반포대로27길 13,280,16.63,80000.0,24750000.0,2천4백75만,1억3백0만,8만,79만
36,용산구,백범로99길40,1086,19.00,80000.0,22840000.0,2천2백84만,1억9천7백0만7만,8만,65만
37,동작구,노량진로8길55,272,15.73,100000.0,33040000.0,3천3백0만4만,1억1천4백42만,10만,72만
38,강서구,공항대로59가길14,285,15.00,60000.0,18630000.0,1천8백63만,6천2백0만,6만,44만
39,동대문구,망우로21나길6,99,14.00,70000.0,19290000.0,1천9백29만,7천4백0만8만,7만,67만
40,강서구,강서로145,57,14.35,50000.0,14960000.0,1천4백96만,6천0만4만,5만,45만
41,강서구,공항대로543,500,18.00,240000.0,29040000.0,2천9백0만4만,9천6백80만,24만,71만
42,마포구,양화로72,913,17.00,370000.0,61200000.0,6천1백20만,1억3천7백60만,37만,1백12만
43,서대문구,경기대로22,499,15.00,290000.0,36400000.0,3천6백40만,1억1천2백80만,29만,78만
44,서초구,남부순환로 2567,379,17.00,290000.0,68000000.0,6천8백0만,1억5천9백0만,29만,81만
45,강남구,논현로 423,78,16.00,410000.0,4900000.0,4백90만,1억2천3백0만,41만,86만
46,광진구,구의강변로 57,70,16.00,340000.0,44000000.0,4천4백0만,8천9백0만,34만,71만
47,강남구,논현동 278-4,283,14.00,240000.0,31620000.0,3천1백62만,1억5백48만,24만,68만
48,관악구,남부순환로180길 6,299,17.00,340000.0,37000000.0,3천7백0만,9천8백0만,34만,85만
49,영등포구,신길동 173-6,162,16.00,290000.0,37000000.0,3천7백0만,1억5천2백0만,29만,79만

In [74]:
ansim2['fnMoneyRentalLow'][12] = '62000'

/tmp/ipykernel_16746/82292642.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  ansim2['fnMoneyRentalLow'][12] = '62000'
/tmp/ipykernel_16746/82292642.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ansim2['fnMoneyRentalLow'][12] = '62000'

In [75]:
# 리스트 컴프리헨션을 사용하여 각 문자열에서 'a'를 'x'로 바꾸기
ansim2['fnMoneyRentalLow'] = [''.join(['0000' if char == '만' else char for char in word]) for word in ansim2['fnMoneyRentalLow']]

/tmp/ipykernel_16746/230215164.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ansim2['fnMoneyRentalLow'] = [''.join(['0000' if char == '만' else char for char in word]) for word in ansim2['fnMoneyRentalLow']]

In [76]:
ansim2

,adresGu,adresRo,scaleTot,roomTotArea,moneyRentalLow,moneyDepositLow,fnMoneyDepositLow,fnMoneyDepositHigh,fnMoneyRentalLow,fnMoneyRentalHigh
0,은평구,갈현동 456-25,163,17.00,290000.0,40000000.0,4천0만,8천6백0만,290000,53만
1,중랑구,상봉동 118-8,299,18.03,280000.0,43000000.0,4천3백0만,1억3천2백0만,280000,76만
2,중랑구,봉우재로 111,83,17.02,300000.0,36000000.0,3천6백0만,7천6백0만,300000,60만
3,은평구,서오릉로 165,238,17.00,290000.0,36000000.0,3천6백0만,9천1백0만,290000,67만
4,동작구,노량진동 54-1,299,17.78,310000.0,45000000.0,4천5백0만,1억9천1백0만,310000,1백0만6만
5,동작구,대방동 403-14,110,18.00,240000.0,34000000.0,3천4백0만,1억2천8백0만,240000,73만
6,송파구,문정동 55-6,438,16.00,360000.0,42000000.0,4천2백0만,1억1천6백0만,360000,86만
7,송파구,잠실동 187-10,217,17.00,330000.0,46000000.0,4천6백0만,1억7천7백0만,330000,1백0만3만
8,성동구,천호대로416,170,14.00,340000.0,38000000.0,3천8백0만,8천0만,340000,63만
9,종로구,숭인동 240-1,139,20.00,340000.0,44800000.0,4천4백80만,1억4천4백0만,340000,85만
10,도봉구,도봉로 445,288,17.00,260000.0,26400000.0,2천6백40만,7천8백40만,260000,69만
11,은평구,불광동 323-21,264,17.05,260000.0,40000000.0,4천0만,1억1천0만,260000,67만
12,마포구,서강로75-4,589,17.00,62000.0,37130000.0,3천7백13만,1억9천0만95만5천0,62000,47만6천0
13,종로구,난계로29길55,238,16.00,300000.0,30600000.0,3천0만60만,8천7백40만,300000,76만
15,영등포구,당산동2가 45-5,496,17.00,310000.0,58000000.0,5천8백0만,1억6천6백0만,310000,71만
16,동대문구,망우로 46,582,15.00,100000.0,54000000.0,5천4백0만,2억2천2백0만,100000,51만
17,은평구,대조동 2-9,977,17.00,90000.0,56000000.0,5천6백0만,2억6천1백0만,90000,60만
18,서대문구,수색로6길 8,124,17.00,400000.0,4400000.0,4백40만,1억3백0만,400000,89만
19,도봉구,삼양로602,253,20.00,350000.0,38250000.0,3천8백25만,7천6백0만4만,350000,59만
20,광진구,천호대로 517,299,16.00,350000.0,44000000.0,4천4백0만,1억1천3백0만,350000,79만
21,송파구,석촌호수로 74,298,16.00,350000.0,39000000.0,3천9백0만,1천1백10만,350000,77만
22,광진구,구의강변로 51,98,15.51,370000.0,46000000.0,4천6백0만,1억2백60만,370000,73만
23,노원구,동일로 1000,270,16.30,300000.0,32000000.0,3천2백0만,9천9백0만,300000,81만
24,중랑구,공릉로2길 8-4,235,16.00,250000.0,27790000.0,2천7백79만,7천6백36만,250000,51만
25,강서구,강서로56길 44,252,15.33,220000.0,38000000.0,3천8백0만,9천6백0만,220000,58만
26,광진구,구의강변로 53,74,16.00,190000.0,28240000.0,2천8백24만,1억5백0만9만,190000,59만
27,영등포구,도신로 59,99,16.12,190000.0,35000000.0,3천5백0만,1억2천2백0만,190000,67만
28,강서구,화곡로 146,82,20.08,80000.0,50000000.0,5천0만,2억,80000,71만
29,용산구,원효로97길 15,751,15.00,240000.0,50340000.0,5천0만34만,1억8천4백80만,240000,93만
30,관악구,남부순환로224길 25,201,15.00,290000.0,24000000.0,2천4백0만,1억3백0만,290000,91만
31,강서구,강서로 231,429,17.00,250000.0,3680000.0,3백68만,1억4백0만,250000,65만
32,강남구,봉은사로 125,297,14.00,380000.0,41570000.0,4천1백57만,1억4천7백44만,380000,95만
33,마포구,토정로131,95,17.00,470000.0,17000000.0,1천7백0만,1억2천9백0만,470000,99만
34,강동구,천호대로989,223,14.00,270000.0,11050000.0,1천1백0만5만,7천9백81만,270000,71만
35,서초구,반포대로27길 13,280,16.63,80000.0,24750000.0,2천4백75만,1억3백0만,80000,79만
36,용산구,백범로99길40,1086,19.00,80000.0,22840000.0,2천2백84만,1억9천7백0만7만,80000,65만
37,동작구,노량진로8길55,272,15.73,100000.0,33040000.0,3천3백0만4만,1억1천4백42만,100000,72만
38,강서구,공항대로59가길14,285,15.00,60000.0,18630000.0,1천8백63만,6천2백0만,60000,44만
39,동대문구,망우로21나길6,99,14.00,70000.0,19290000.0,1천9백29만,7천4백0만8만,70000,67만
40,강서구,강서로145,57,14.35,50000.0,14960000.0,1천4백96만,6천0만4만,50000,45만
41,강서구,공항대로543,500,18.00,240000.0,29040000.0,2천9백0만4만,9천6백80만,240000,71만
42,마포구,양화로72,913,17.00,370000.0,61200000.0,6천1백20만,1억3천7백60만,370000,1백12만
43,서대문구,경기대로22,499,15.00,290000.0,36400000.0,3천6백40만,1억1천2백80만,290000,78만
44,서초구,남부순환로 2567,379,17.00,290000.0,68000000.0,6천8백0만,1억5천9백0만,290000,81만
45,강남구,논현로 423,78,16.00,410000.0,4900000.0,4백90만,1억2천3백0만,410000,86만
46,광진구,구의강변로 57,70,16.00,340000.0,44000000.0,4천4백0만,8천9백0만,340000,71만
47,강남구,논현동 278-4,283,14.00,240000.0,31620000.0,3천1백62만,1억5백48만,240000,68만
48,관악구,남부순환로180길 6,299,17.00,340000.0,37000000.0,3천7백0만,9천8백0만,340000,85만
49,영등포구,신길동 173-6,162,16.00,290000.0,37000000.0,3천7백0만,1억5천2백0만,290000,79만

In [77]:
ansim2['fnMoneyRentalHigh']

0        53만
1        76만
2        60만
3        67만
4     1백0만6만
5        73만
6        86만
7     1백0만3만
8        63만
9        85만
10       69만
11       67만
12    47만6천0
13       76만
15       71만
16       51만
17       60만
18       89만
19       59만
20       79만
21       77만
22       73만
23       81만
24       51만
25       58만
26       59만
27       67만
28       71만
29       93만
30       91만
31       65만
32       95만
33       99만
34       71만
35       79만
36       65만
37       72만
38       44만
39       67만
40       45만
41       71만
42     1백12만
43       78만
44       81만
45       86만
46       71만
47       68만
48       85만
49       79만
Name: fnMoneyRentalHigh, dtype: object

In [78]:
ansim2['fnMoneyRentalHigh'][4] = '1060000'
ansim2['fnMoneyRentalHigh'][7] = '1030000'
ansim2['fnMoneyRentalHigh'][12] = '476000'
ansim2['fnMoneyRentalHigh'][42] = '1120000'

/tmp/ipykernel_16746/995886632.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ansim2['fnMoneyRentalHigh'][4] = '1060000'
/tmp/ipykernel_16746/995886632.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ansim2['fnMoneyRentalHigh'][7] = '1030000'
/tmp/ipykernel_16746/995886632.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ansim2['fnMoneyRentalHigh'][12] = '476000'
/tmp/ipykernel_16746/995886632.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ansim2['fnMoneyRentalHigh'][42] = '1120000'

In [79]:
# 리스트 컴프리헨션을 사용하여 각 문자열에서 'a'를 'x'로 바꾸기
ansim2['fnMoneyRentalHigh'] = [''.join(['0000' if char == '만' else char for char in word]) for word in ansim2['fnMoneyRentalHigh']]

/tmp/ipykernel_16746/1324027442.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ansim2['fnMoneyRentalHigh'] = [''.join(['0000' if char == '만' else char for char in word]) for word in ansim2['fnMoneyRentalHigh']]

In [80]:
ansim2

,adresGu,adresRo,scaleTot,roomTotArea,moneyRentalLow,moneyDepositLow,fnMoneyDepositLow,fnMoneyDepositHigh,fnMoneyRentalLow,fnMoneyRentalHigh
0,은평구,갈현동 456-25,163,17.00,290000.0,40000000.0,4천0만,8천6백0만,290000,530000
1,중랑구,상봉동 118-8,299,18.03,280000.0,43000000.0,4천3백0만,1억3천2백0만,280000,760000
2,중랑구,봉우재로 111,83,17.02,300000.0,36000000.0,3천6백0만,7천6백0만,300000,600000
3,은평구,서오릉로 165,238,17.00,290000.0,36000000.0,3천6백0만,9천1백0만,290000,670000
4,동작구,노량진동 54-1,299,17.78,310000.0,45000000.0,4천5백0만,1억9천1백0만,310000,1060000
5,동작구,대방동 403-14,110,18.00,240000.0,34000000.0,3천4백0만,1억2천8백0만,240000,730000
6,송파구,문정동 55-6,438,16.00,360000.0,42000000.0,4천2백0만,1억1천6백0만,360000,860000
7,송파구,잠실동 187-10,217,17.00,330000.0,46000000.0,4천6백0만,1억7천7백0만,330000,1030000
8,성동구,천호대로416,170,14.00,340000.0,38000000.0,3천8백0만,8천0만,340000,630000
9,종로구,숭인동 240-1,139,20.00,340000.0,44800000.0,4천4백80만,1억4천4백0만,340000,850000
10,도봉구,도봉로 445,288,17.00,260000.0,26400000.0,2천6백40만,7천8백40만,260000,690000
11,은평구,불광동 323-21,264,17.05,260000.0,40000000.0,4천0만,1억1천0만,260000,670000
12,마포구,서강로75-4,589,17.00,62000.0,37130000.0,3천7백13만,1억9천0만95만5천0,62000,476000
13,종로구,난계로29길55,238,16.00,300000.0,30600000.0,3천0만60만,8천7백40만,300000,760000
15,영등포구,당산동2가 45-5,496,17.00,310000.0,58000000.0,5천8백0만,1억6천6백0만,310000,710000
16,동대문구,망우로 46,582,15.00,100000.0,54000000.0,5천4백0만,2억2천2백0만,100000,510000
17,은평구,대조동 2-9,977,17.00,90000.0,56000000.0,5천6백0만,2억6천1백0만,90000,600000
18,서대문구,수색로6길 8,124,17.00,400000.0,4400000.0,4백40만,1억3백0만,400000,890000
19,도봉구,삼양로602,253,20.00,350000.0,38250000.0,3천8백25만,7천6백0만4만,350000,590000
20,광진구,천호대로 517,299,16.00,350000.0,44000000.0,4천4백0만,1억1천3백0만,350000,790000
21,송파구,석촌호수로 74,298,16.00,350000.0,39000000.0,3천9백0만,1천1백10만,350000,770000
22,광진구,구의강변로 51,98,15.51,370000.0,46000000.0,4천6백0만,1억2백60만,370000,730000
23,노원구,동일로 1000,270,16.30,300000.0,32000000.0,3천2백0만,9천9백0만,300000,810000
24,중랑구,공릉로2길 8-4,235,16.00,250000.0,27790000.0,2천7백79만,7천6백36만,250000,510000
25,강서구,강서로56길 44,252,15.33,220000.0,38000000.0,3천8백0만,9천6백0만,220000,580000
26,광진구,구의강변로 53,74,16.00,190000.0,28240000.0,2천8백24만,1억5백0만9만,190000,590000
27,영등포구,도신로 59,99,16.12,190000.0,35000000.0,3천5백0만,1억2천2백0만,190000,670000
28,강서구,화곡로 146,82,20.08,80000.0,50000000.0,5천0만,2억,80000,710000
29,용산구,원효로97길 15,751,15.00,240000.0,50340000.0,5천0만34만,1억8천4백80만,240000,930000
30,관악구,남부순환로224길 25,201,15.00,290000.0,24000000.0,2천4백0만,1억3백0만,290000,910000
31,강서구,강서로 231,429,17.00,250000.0,3680000.0,3백68만,1억4백0만,250000,650000
32,강남구,봉은사로 125,297,14.00,380000.0,41570000.0,4천1백57만,1억4천7백44만,380000,950000
33,마포구,토정로131,95,17.00,470000.0,17000000.0,1천7백0만,1억2천9백0만,470000,990000
34,강동구,천호대로989,223,14.00,270000.0,11050000.0,1천1백0만5만,7천9백81만,270000,710000
35,서초구,반포대로27길 13,280,16.63,80000.0,24750000.0,2천4백75만,1억3백0만,80000,790000
36,용산구,백범로99길40,1086,19.00,80000.0,22840000.0,2천2백84만,1억9천7백0만7만,80000,650000
37,동작구,노량진로8길55,272,15.73,100000.0,33040000.0,3천3백0만4만,1억1천4백42만,100000,720000
38,강서구,공항대로59가길14,285,15.00,60000.0,18630000.0,1천8백63만,6천2백0만,60000,440000
39,동대문구,망우로21나길6,99,14.00,70000.0,19290000.0,1천9백29만,7천4백0만8만,70000,670000
40,강서구,강서로145,57,14.35,50000.0,14960000.0,1천4백96만,6천0만4만,50000,450000
41,강서구,공항대로543,500,18.00,240000.0,29040000.0,2천9백0만4만,9천6백80만,240000,710000
42,마포구,양화로72,913,17.00,370000.0,61200000.0,6천1백20만,1억3천7백60만,370000,1120000
43,서대문구,경기대로22,499,15.00,290000.0,36400000.0,3천6백40만,1억1천2백80만,290000,780000
44,서초구,남부순환로 2567,379,17.00,290000.0,68000000.0,6천8백0만,1억5천9백0만,290000,810000
45,강남구,논현로 423,78,16.00,410000.0,4900000.0,4백90만,1억2천3백0만,410000,860000
46,광진구,구의강변로 57,70,16.00,340000.0,44000000.0,4천4백0만,8천9백0만,340000,710000
47,강남구,논현동 278-4,283,14.00,240000.0,31620000.0,3천1백62만,1억5백48만,240000,680000
48,관악구,남부순환로180길 6,299,17.00,340000.0,37000000.0,3천7백0만,9천8백0만,340000,850000
49,영등포구,신길동 173-6,162,16.00,290000.0,37000000.0,3천7백0만,1억5천2백0만,290000,790000

In [81]:
ansim2['fnMoneyDepositLow']

0         4천0만
1       4천3백0만
2       3천6백0만
3       3천6백0만
4       4천5백0만
5       3천4백0만
6       4천2백0만
7       4천6백0만
8       3천8백0만
9      4천4백80만
10     2천6백40만
11        4천0만
12     3천7백13만
13     3천0만60만
15      5천8백0만
16      5천4백0만
17      5천6백0만
18       4백40만
19     3천8백25만
20      4천4백0만
21      3천9백0만
22      4천6백0만
23      3천2백0만
24     2천7백79만
25      3천8백0만
26     2천8백24만
27      3천5백0만
28        5천0만
29     5천0만34만
30      2천4백0만
31       3백68만
32     4천1백57만
33      1천7백0만
34    1천1백0만5만
35     2천4백75만
36     2천2백84만
37    3천3백0만4만
38     1천8백63만
39     1천9백29만
40     1천4백96만
41    2천9백0만4만
42     6천1백20만
43     3천6백40만
44      6천8백0만
45       4백90만
46      4천4백0만
47     3천1백62만
48      3천7백0만
49      3천7백0만
Name: fnMoneyDepositLow, dtype: object

In [82]:
# 주어진 리스트
a = ansim2['fnMoneyDepositLow'].tolist()
b = ansim2['fnMoneyDepositHigh'].tolist()

# '백0만'을 '백만'으로, '천0만'을 '천만'으로 바꾸는 함수
def replace_baek(word):
    return word.replace('백0만', '백만').replace('천0만', '천만')

# 각 문자열에서 '백0만'을 '백만'으로, '천0만'을 '천만'으로 바꾸기
new_list = [replace_baek(word) for word in a]
new_list2 = [replace_baek(word) for word in b]

# 결과 출력
print(new_list)

ansim2['fnMoneyDepositLow'] = new_list
ansim2['fnMoneyDepositHigh'] = new_list2

['4천만', '4천3백만', '3천6백만', '3천6백만', '4천5백만', '3천4백만', '4천2백만', '4천6백만', '3천8백만', '4천4백80만', '2천6백40만', '4천만', '3천7백13만', '3천만60만', '5천8백만', '5천4백만', '5천6백만', '4백40만', '3천8백25만', '4천4백만', '3천9백만', '4천6백만', '3천2백만', '2천7백79만', '3천8백만', '2천8백24만', '3천5백만', '5천만', '5천만34만', '2천4백만', '3백68만', '4천1백57만', '1천7백만', '1천1백만5만', '2천4백75만', '2천2백84만', '3천3백만4만', '1천8백63만', '1천9백29만', '1천4백96만', '2천9백만4만', '6천1백20만', '3천6백40만', '6천8백만', '4백90만', '4천4백만', '3천1백62만', '3천7백만', '3천7백만']

/tmp/ipykernel_16746/1979941606.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ansim2['fnMoneyDepositLow'] = new_list
/tmp/ipykernel_16746/1979941606.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ansim2['fnMoneyDepositHigh'] = new_list2

In [83]:
ansim2

,adresGu,adresRo,scaleTot,roomTotArea,moneyRentalLow,moneyDepositLow,fnMoneyDepositLow,fnMoneyDepositHigh,fnMoneyRentalLow,fnMoneyRentalHigh
0,은평구,갈현동 456-25,163,17.00,290000.0,40000000.0,4천만,8천6백만,290000,530000
1,중랑구,상봉동 118-8,299,18.03,280000.0,43000000.0,4천3백만,1억3천2백만,280000,760000
2,중랑구,봉우재로 111,83,17.02,300000.0,36000000.0,3천6백만,7천6백만,300000,600000
3,은평구,서오릉로 165,238,17.00,290000.0,36000000.0,3천6백만,9천1백만,290000,670000
4,동작구,노량진동 54-1,299,17.78,310000.0,45000000.0,4천5백만,1억9천1백만,310000,1060000
5,동작구,대방동 403-14,110,18.00,240000.0,34000000.0,3천4백만,1억2천8백만,240000,730000
6,송파구,문정동 55-6,438,16.00,360000.0,42000000.0,4천2백만,1억1천6백만,360000,860000
7,송파구,잠실동 187-10,217,17.00,330000.0,46000000.0,4천6백만,1억7천7백만,330000,1030000
8,성동구,천호대로416,170,14.00,340000.0,38000000.0,3천8백만,8천만,340000,630000
9,종로구,숭인동 240-1,139,20.00,340000.0,44800000.0,4천4백80만,1억4천4백만,340000,850000
10,도봉구,도봉로 445,288,17.00,260000.0,26400000.0,2천6백40만,7천8백40만,260000,690000
11,은평구,불광동 323-21,264,17.05,260000.0,40000000.0,4천만,1억1천만,260000,670000
12,마포구,서강로75-4,589,17.00,62000.0,37130000.0,3천7백13만,1억9천만95만5천0,62000,476000
13,종로구,난계로29길55,238,16.00,300000.0,30600000.0,3천만60만,8천7백40만,300000,760000
15,영등포구,당산동2가 45-5,496,17.00,310000.0,58000000.0,5천8백만,1억6천6백만,310000,710000
16,동대문구,망우로 46,582,15.00,100000.0,54000000.0,5천4백만,2억2천2백만,100000,510000
17,은평구,대조동 2-9,977,17.00,90000.0,56000000.0,5천6백만,2억6천1백만,90000,600000
18,서대문구,수색로6길 8,124,17.00,400000.0,4400000.0,4백40만,1억3백만,400000,890000
19,도봉구,삼양로602,253,20.00,350000.0,38250000.0,3천8백25만,7천6백만4만,350000,590000
20,광진구,천호대로 517,299,16.00,350000.0,44000000.0,4천4백만,1억1천3백만,350000,790000
21,송파구,석촌호수로 74,298,16.00,350000.0,39000000.0,3천9백만,1천1백10만,350000,770000
22,광진구,구의강변로 51,98,15.51,370000.0,46000000.0,4천6백만,1억2백60만,370000,730000
23,노원구,동일로 1000,270,16.30,300000.0,32000000.0,3천2백만,9천9백만,300000,810000
24,중랑구,공릉로2길 8-4,235,16.00,250000.0,27790000.0,2천7백79만,7천6백36만,250000,510000
25,강서구,강서로56길 44,252,15.33,220000.0,38000000.0,3천8백만,9천6백만,220000,580000
26,광진구,구의강변로 53,74,16.00,190000.0,28240000.0,2천8백24만,1억5백만9만,190000,590000
27,영등포구,도신로 59,99,16.12,190000.0,35000000.0,3천5백만,1억2천2백만,190000,670000
28,강서구,화곡로 146,82,20.08,80000.0,50000000.0,5천만,2억,80000,710000
29,용산구,원효로97길 15,751,15.00,240000.0,50340000.0,5천만34만,1억8천4백80만,240000,930000
30,관악구,남부순환로224길 25,201,15.00,290000.0,24000000.0,2천4백만,1억3백만,290000,910000
31,강서구,강서로 231,429,17.00,250000.0,3680000.0,3백68만,1억4백만,250000,650000
32,강남구,봉은사로 125,297,14.00,380000.0,41570000.0,4천1백57만,1억4천7백44만,380000,950000
33,마포구,토정로131,95,17.00,470000.0,17000000.0,1천7백만,1억2천9백만,470000,990000
34,강동구,천호대로989,223,14.00,270000.0,11050000.0,1천1백만5만,7천9백81만,270000,710000
35,서초구,반포대로27길 13,280,16.63,80000.0,24750000.0,2천4백75만,1억3백만,80000,790000
36,용산구,백범로99길40,1086,19.00,80000.0,22840000.0,2천2백84만,1억9천7백만7만,80000,650000
37,동작구,노량진로8길55,272,15.73,100000.0,33040000.0,3천3백만4만,1억1천4백42만,100000,720000
38,강서구,공항대로59가길14,285,15.00,60000.0,18630000.0,1천8백63만,6천2백만,60000,440000
39,동대문구,망우로21나길6,99,14.00,70000.0,19290000.0,1천9백29만,7천4백만8만,70000,670000
40,강서구,강서로145,57,14.35,50000.0,14960000.0,1천4백96만,6천만4만,50000,450000
41,강서구,공항대로543,500,18.00,240000.0,29040000.0,2천9백만4만,9천6백80만,240000,710000
42,마포구,양화로72,913,17.00,370000.0,61200000.0,6천1백20만,1억3천7백60만,370000,1120000
43,서대문구,경기대로22,499,15.00,290000.0,36400000.0,3천6백40만,1억1천2백80만,290000,780000
44,서초구,남부순환로 2567,379,17.00,290000.0,68000000.0,6천8백만,1억5천9백만,290000,810000
45,강남구,논현로 423,78,16.00,410000.0,4900000.0,4백90만,1억2천3백만,410000,860000
46,광진구,구의강변로 57,70,16.00,340000.0,44000000.0,4천4백만,8천9백만,340000,710000
47,강남구,논현동 278-4,283,14.00,240000.0,31620000.0,3천1백62만,1억5백48만,240000,680000
48,관악구,남부순환로180길 6,299,17.00,340000.0,37000000.0,3천7백만,9천8백만,340000,850000
49,영등포구,신길동 173-6,162,16.00,290000.0,37000000.0,3천7백만,1억5천2백만,290000,790000

In [84]:
c = ansim2['fnMoneyDepositLow'].tolist()
d = ansim2['fnMoneyDepositHigh'].tolist()

In [85]:
import re

# 주어진 문자열 리스트
strings = ['4천만', '4천3백만', '3천6백만', '1억9천1백만']

# 정규식 패턴 정의
pattern = re.compile(r'(\d+)(천|백|만|억)?')

# 문자열을 숫자로 변환하는 함수
def convert_to_number(word):
    number = 0
    matches = pattern.findall(word)
    for match in matches:
        digit = int(match[0])
        unit = match[1]
        if unit == '천':
            digit *= 10000000
        elif unit == '백':
            digit *= 1000000
        elif unit == '만':
            digit *= 10000
        elif unit == '억':
            digit *= 100000000  # 억 단위는 1억 = 1e8
        else:
            digit *= 1
        number += digit
    return number

# 각 문자열을 숫자로 변환하여 리스트 생성
new_list = [convert_to_number(word) for word in c]
new_list2 = [convert_to_number(word) for word in d]

# 결과 출력
print(new_list)

[40000000, 43000000, 36000000, 36000000, 45000000, 34000000, 42000000, 46000000, 38000000, 44800000, 26400000, 40000000, 37130000, 30600000, 58000000, 54000000, 56000000, 4400000, 38250000, 44000000, 39000000, 46000000, 32000000, 27790000, 38000000, 28240000, 35000000, 50000000, 50340000, 24000000, 3680000, 41570000, 17000000, 11050000, 24750000, 22840000, 33040000, 18630000, 19290000, 14960000, 29040000, 61200000, 36400000, 68000000, 4900000, 44000000, 31620000, 37000000, 37000000]

In [86]:
ansim2['fnMoneyDepositLow'] = new_list
ansim2['fnMoneyDepositHigh'] = new_list2

/tmp/ipykernel_16746/3633027788.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ansim2['fnMoneyDepositLow'] = new_list
/tmp/ipykernel_16746/3633027788.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ansim2['fnMoneyDepositHigh'] = new_list2

In [87]:
ansim2

,adresGu,adresRo,scaleTot,roomTotArea,moneyRentalLow,moneyDepositLow,fnMoneyDepositLow,fnMoneyDepositHigh,fnMoneyRentalLow,fnMoneyRentalHigh
0,은평구,갈현동 456-25,163,17.00,290000.0,40000000.0,40000000,86000000,290000,530000
1,중랑구,상봉동 118-8,299,18.03,280000.0,43000000.0,43000000,132000000,280000,760000
2,중랑구,봉우재로 111,83,17.02,300000.0,36000000.0,36000000,76000000,300000,600000
3,은평구,서오릉로 165,238,17.00,290000.0,36000000.0,36000000,91000000,290000,670000
4,동작구,노량진동 54-1,299,17.78,310000.0,45000000.0,45000000,191000000,310000,1060000
5,동작구,대방동 403-14,110,18.00,240000.0,34000000.0,34000000,128000000,240000,730000
6,송파구,문정동 55-6,438,16.00,360000.0,42000000.0,42000000,116000000,360000,860000
7,송파구,잠실동 187-10,217,17.00,330000.0,46000000.0,46000000,177000000,330000,1030000
8,성동구,천호대로416,170,14.00,340000.0,38000000.0,38000000,80000000,340000,630000
9,종로구,숭인동 240-1,139,20.00,340000.0,44800000.0,44800000,144000000,340000,850000
10,도봉구,도봉로 445,288,17.00,260000.0,26400000.0,26400000,78400000,260000,690000
11,은평구,불광동 323-21,264,17.05,260000.0,40000000.0,40000000,110000000,260000,670000
12,마포구,서강로75-4,589,17.00,62000.0,37130000.0,37130000,240950000,62000,476000
13,종로구,난계로29길55,238,16.00,300000.0,30600000.0,30600000,87400000,300000,760000
15,영등포구,당산동2가 45-5,496,17.00,310000.0,58000000.0,58000000,166000000,310000,710000
16,동대문구,망우로 46,582,15.00,100000.0,54000000.0,54000000,222000000,100000,510000
17,은평구,대조동 2-9,977,17.00,90000.0,56000000.0,56000000,261000000,90000,600000
18,서대문구,수색로6길 8,124,17.00,400000.0,4400000.0,4400000,103000000,400000,890000
19,도봉구,삼양로602,253,20.00,350000.0,38250000.0,38250000,76040000,350000,590000
20,광진구,천호대로 517,299,16.00,350000.0,44000000.0,44000000,113000000,350000,790000
21,송파구,석촌호수로 74,298,16.00,350000.0,39000000.0,39000000,11100000,350000,770000
22,광진구,구의강변로 51,98,15.51,370000.0,46000000.0,46000000,102600000,370000,730000
23,노원구,동일로 1000,270,16.30,300000.0,32000000.0,32000000,99000000,300000,810000
24,중랑구,공릉로2길 8-4,235,16.00,250000.0,27790000.0,27790000,76360000,250000,510000
25,강서구,강서로56길 44,252,15.33,220000.0,38000000.0,38000000,96000000,220000,580000
26,광진구,구의강변로 53,74,16.00,190000.0,28240000.0,28240000,105090000,190000,590000
27,영등포구,도신로 59,99,16.12,190000.0,35000000.0,35000000,122000000,190000,670000
28,강서구,화곡로 146,82,20.08,80000.0,50000000.0,50000000,200000000,80000,710000
29,용산구,원효로97길 15,751,15.00,240000.0,50340000.0,50340000,184800000,240000,930000
30,관악구,남부순환로224길 25,201,15.00,290000.0,24000000.0,24000000,103000000,290000,910000
31,강서구,강서로 231,429,17.00,250000.0,3680000.0,3680000,104000000,250000,650000
32,강남구,봉은사로 125,297,14.00,380000.0,41570000.0,41570000,147440000,380000,950000
33,마포구,토정로131,95,17.00,470000.0,17000000.0,17000000,129000000,470000,990000
34,강동구,천호대로989,223,14.00,270000.0,11050000.0,11050000,79810000,270000,710000
35,서초구,반포대로27길 13,280,16.63,80000.0,24750000.0,24750000,103000000,80000,790000
36,용산구,백범로99길40,1086,19.00,80000.0,22840000.0,22840000,197070000,80000,650000
37,동작구,노량진로8길55,272,15.73,100000.0,33040000.0,33040000,114420000,100000,720000
38,강서구,공항대로59가길14,285,15.00,60000.0,18630000.0,18630000,62000000,60000,440000
39,동대문구,망우로21나길6,99,14.00,70000.0,19290000.0,19290000,74080000,70000,670000
40,강서구,강서로145,57,14.35,50000.0,14960000.0,14960000,60040000,50000,450000
41,강서구,공항대로543,500,18.00,240000.0,29040000.0,29040000,96800000,240000,710000
42,마포구,양화로72,913,17.00,370000.0,61200000.0,61200000,137600000,370000,1120000
43,서대문구,경기대로22,499,15.00,290000.0,36400000.0,36400000,112800000,290000,780000
44,서초구,남부순환로 2567,379,17.00,290000.0,68000000.0,68000000,159000000,290000,810000
45,강남구,논현로 423,78,16.00,410000.0,4900000.0,4900000,123000000,410000,860000
46,광진구,구의강변로 57,70,16.00,340000.0,44000000.0,44000000,89000000,340000,710000
47,강남구,논현동 278-4,283,14.00,240000.0,31620000.0,31620000,105480000,240000,680000
48,관악구,남부순환로180길 6,299,17.00,340000.0,37000000.0,37000000,98000000,340000,850000
49,영등포구,신길동 173-6,162,16.00,290000.0,37000000.0,37000000,152000000,290000,790000

In [88]:
ansim2[['moneyDepositLow', 'fnMoneyRentalLow','fnMoneyRentalHigh','roomTotArea','moneyRentalLow']] \
= ansim2[['moneyDepositLow', 'fnMoneyRentalLow','fnMoneyRentalHigh','roomTotArea','moneyRentalLow']].astype(int)

/tmp/ipykernel_16746/198632435.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ansim2[['moneyDepositLow', 'fnMoneyRentalLow','fnMoneyRentalHigh','roomTotArea','moneyRentalLow']] \

In [89]:
ansim2.info()

<class 'pandas.core.frame.DataFrame'>
Index: 49 entries, 0 to 49
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   adresGu             49 non-null     object
 1   adresRo             49 non-null     object
 2   scaleTot            49 non-null     object
 3   roomTotArea         49 non-null     int64
 4   moneyRentalLow      49 non-null     int64
 5   moneyDepositLow     49 non-null     int64
 6   fnMoneyDepositLow   49 non-null     int64
 7   fnMoneyDepositHigh  49 non-null     int64
 8   fnMoneyRentalLow    49 non-null     int64
 9   fnMoneyRentalHigh   49 non-null     int64
dtypes: int64(7), object(3)
memory usage: 5.3+ KB

In [90]:
ansim2['kindRental']='청년안심'

/tmp/ipykernel_16746/915585506.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ansim2['kindRental']='청년안심'

In [91]:
ansim2['kindHouse']='아파트'

/tmp/ipykernel_16746/3317905746.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ansim2['kindHouse']='아파트'

In [92]:
ansim2

,adresGu,adresRo,scaleTot,roomTotArea,moneyRentalLow,moneyDepositLow,fnMoneyDepositLow,fnMoneyDepositHigh,fnMoneyRentalLow,fnMoneyRentalHigh,kindRental,kindHouse
0,은평구,갈현동 456-25,163,17,290000,40000000,40000000,86000000,290000,530000,청년안심,아파트
1,중랑구,상봉동 118-8,299,18,280000,43000000,43000000,132000000,280000,760000,청년안심,아파트
2,중랑구,봉우재로 111,83,17,300000,36000000,36000000,76000000,300000,600000,청년안심,아파트
3,은평구,서오릉로 165,238,17,290000,36000000,36000000,91000000,290000,670000,청년안심,아파트
4,동작구,노량진동 54-1,299,17,310000,45000000,45000000,191000000,310000,1060000,청년안심,아파트
5,동작구,대방동 403-14,110,18,240000,34000000,34000000,128000000,240000,730000,청년안심,아파트
6,송파구,문정동 55-6,438,16,360000,42000000,42000000,116000000,360000,860000,청년안심,아파트
7,송파구,잠실동 187-10,217,17,330000,46000000,46000000,177000000,330000,1030000,청년안심,아파트
8,성동구,천호대로416,170,14,340000,38000000,38000000,80000000,340000,630000,청년안심,아파트
9,종로구,숭인동 240-1,139,20,340000,44800000,44800000,144000000,340000,850000,청년안심,아파트
10,도봉구,도봉로 445,288,17,260000,26400000,26400000,78400000,260000,690000,청년안심,아파트
11,은평구,불광동 323-21,264,17,260000,40000000,40000000,110000000,260000,670000,청년안심,아파트
12,마포구,서강로75-4,589,17,62000,37130000,37130000,240950000,62000,476000,청년안심,아파트
13,종로구,난계로29길55,238,16,300000,30600000,30600000,87400000,300000,760000,청년안심,아파트
15,영등포구,당산동2가 45-5,496,17,310000,58000000,58000000,166000000,310000,710000,청년안심,아파트
16,동대문구,망우로 46,582,15,100000,54000000,54000000,222000000,100000,510000,청년안심,아파트
17,은평구,대조동 2-9,977,17,90000,56000000,56000000,261000000,90000,600000,청년안심,아파트
18,서대문구,수색로6길 8,124,17,400000,4400000,4400000,103000000,400000,890000,청년안심,아파트
19,도봉구,삼양로602,253,20,350000,38250000,38250000,76040000,350000,590000,청년안심,아파트
20,광진구,천호대로 517,299,16,350000,44000000,44000000,113000000,350000,790000,청년안심,아파트
21,송파구,석촌호수로 74,298,16,350000,39000000,39000000,11100000,350000,770000,청년안심,아파트
22,광진구,구의강변로 51,98,15,370000,46000000,46000000,102600000,370000,730000,청년안심,아파트
23,노원구,동일로 1000,270,16,300000,32000000,32000000,99000000,300000,810000,청년안심,아파트
24,중랑구,공릉로2길 8-4,235,16,250000,27790000,27790000,76360000,250000,510000,청년안심,아파트
25,강서구,강서로56길 44,252,15,220000,38000000,38000000,96000000,220000,580000,청년안심,아파트
26,광진구,구의강변로 53,74,16,190000,28240000,28240000,105090000,190000,590000,청년안심,아파트
27,영등포구,도신로 59,99,16,190000,35000000,35000000,122000000,190000,670000,청년안심,아파트
28,강서구,화곡로 146,82,20,80000,50000000,50000000,200000000,80000,710000,청년안심,아파트
29,용산구,원효로97길 15,751,15,240000,50340000,50340000,184800000,240000,930000,청년안심,아파트
30,관악구,남부순환로224길 25,201,15,290000,24000000,24000000,103000000,290000,910000,청년안심,아파트
31,강서구,강서로 231,429,17,250000,3680000,3680000,104000000,250000,650000,청년안심,아파트
32,강남구,봉은사로 125,297,14,380000,41570000,41570000,147440000,380000,950000,청년안심,아파트
33,마포구,토정로131,95,17,470000,17000000,17000000,129000000,470000,990000,청년안심,아파트
34,강동구,천호대로989,223,14,270000,11050000,11050000,79810000,270000,710000,청년안심,아파트
35,서초구,반포대로27길 13,280,16,80000,24750000,24750000,103000000,80000,790000,청년안심,아파트
36,용산구,백범로99길40,1086,19,80000,22840000,22840000,197070000,80000,650000,청년안심,아파트
37,동작구,노량진로8길55,272,15,100000,33040000,33040000,114420000,100000,720000,청년안심,아파트
38,강서구,공항대로59가길14,285,15,60000,18630000,18630000,62000000,60000,440000,청년안심,아파트
39,동대문구,망우로21나길6,99,14,70000,19290000,19290000,74080000,70000,670000,청년안심,아파트
40,강서구,강서로145,57,14,50000,14960000,14960000,60040000,50000,450000,청년안심,아파트
41,강서구,공항대로543,500,18,240000,29040000,29040000,96800000,240000,710000,청년안심,아파트
42,마포구,양화로72,913,17,370000,61200000,61200000,137600000,370000,1120000,청년안심,아파트
43,서대문구,경기대로22,499,15,290000,36400000,36400000,112800000,290000,780000,청년안심,아파트
44,서초구,남부순환로 2567,379,17,290000,68000000,68000000,159000000,290000,810000,청년안심,아파트
45,강남구,논현로 423,78,16,410000,4900000,4900000,123000000,410000,860000,청년안심,아파트
46,광진구,구의강변로 57,70,16,340000,44000000,44000000,89000000,340000,710000,청년안심,아파트
47,강남구,논현동 278-4,283,14,240000,31620000,31620000,105480000,240000,680000,청년안심,아파트
48,관악구,남부순환로180길 6,299,17,340000,37000000,37000000,98000000,340000,850000,청년안심,아파트
49,영등포구,신길동 173-6,162,16,290000,37000000,37000000,152000000,290000,790000,청년안심,아파트

In [93]:
ansim2 = ansim2[['kindRental', 'adresGu', 'adresRo', 'scaleTot', 'kindHouse', 'roomTotArea', 'moneyRentalLow', 'moneyDepositLow',
       'fnMoneyDepositLow', 'fnMoneyDepositHigh', 'fnMoneyRentalLow',
       'fnMoneyRentalHigh']]

In [104]:
import pymysql

In [105]:
import pymysql
import pandas as pd
con = pymysql.connect(host='13.125.65.37', user='encore1', password='EnCore1!@#', db='encore1', charset='utf8')
cur = con.cursor()

In [106]:
sql = """
INSERT INTO ansim VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
"""

In [107]:
ansim2 = ansim2.reset_index(drop=True)

In [108]:
for i in range(len(ansim2)):
    cur.execute(sql, ansim2.iloc[i].tolist())

In [109]:
con.commit()

In [100]:
con.close()

In [103]:
ansim2.head()

,kindRental,adresGu,adresRo,scaleTot,kindHouse,roomTotArea,moneyRentalLow,moneyDepositLow,fnMoneyDepositLow,fnMoneyDepositHigh,fnMoneyRentalLow,fnMoneyRentalHigh
0,청년안심,은평구,갈현동 456-25,163,아파트,17,290000,40000000,40000000,86000000,290000,530000
1,청년안심,중랑구,상봉동 118-8,299,아파트,18,280000,43000000,43000000,132000000,280000,760000
2,청년안심,중랑구,봉우재로 111,83,아파트,17,300000,36000000,36000000,76000000,300000,600000
3,청년안심,은평구,서오릉로 165,238,아파트,17,290000,36000000,36000000,91000000,290000,670000
4,청년안심,동작구,노량진동 54-1,299,아파트,17,310000,45000000,45000000,191000000,310000,1060000